export interface Province {
  cod:string;
  name:string;
}

export var spanishProvinces: Province[] = [
  { cod: '02',  name: 'Albacete'},
  { cod: '03',  name: 'Alicante'},
  { cod: '04',  name: 'Almería'},
  { cod: '01',  name: 'Álava'},
  { cod: '33',  name: 'Asturias'},
  { cod: '05',  name: 'Ávila'},
  { cod: '06',  name: 'Badajoz'},
  { cod: '07',  name: 'Islas Baleares'},
  { cod: '08',  name: 'Barcelona'},
  { cod: '48',  name: 'Bizkaia'},
  { cod: '09',  name: 'Burgos'},
  { cod: '10',  name: 'Cáceres'},
  { cod: '11',  name: 'Cádiz'},
  { cod: '39',  name: 'Cantabria'},
  { cod: '12',  name: 'Castellón'},
  { cod: '13',  name: 'Ciudad Real'},
  { cod: '14',  name: 'Córdoba'},
  { cod: '15',  name: 'A Coruña'},
  { cod: '16',  name: 'Cuenca'},
  { cod: '20',  name: 'Gipuzkoa'},
  { cod: '17',  name: 'Girona'},
  { cod: '18',  name: 'Granada'},
  { cod: '19',  name: 'Guadalajara'},
  { cod: '21',  name: 'Huelva'},
  { cod: '22',  name: 'Huesca'},
  { cod: '23',  name: 'Jaén'},
  { cod: '24',  name: 'León'},
  { cod: '25',  name: 'Lleida'},
  { cod: '27',  name: 'Lugo'},
  { cod: '28',  name: 'Madrid'},
  { cod: '29',  name: 'Málaga'},
  { cod: '30',  name: 'Murcia'},
  { cod: '31',  name: 'Navarra'},
  { cod: '32',  name: 'Ourense'},
  { cod: '34',  name: 'Palencia'},
  { cod: '35',  name: 'Las Palmas'},
  { cod: '36',  name: 'Pontevedra'},
  { cod: '26',  name: 'La Rioja'},
  { cod: '37',  name: 'Salamanca'},
  { cod: '38',  name: 'Santa Cruz de Tenerife'},
  { cod: '40',  name: 'Segovia'},
  { cod: '41',  name: 'Sevilla'},
  { cod: '42',  name: 'Soria'},
  { cod: '43',  name: 'Tarragona'},
  { cod: '44',  name: 'Teruel'},
  { cod: '45',  name: 'Toledo'},
  { cod: '46', name: 'Valencia'},
  { cod: '47', name: 'Valladolid'},
  { cod: '49',  name: 'Zamora'},
  { cod: '50',  name: 'Zaragoza'},
  { cod: '51', name: 'Ceuta'},
  { cod: '52', name: 'Melilla'}
];


